# Static configuration
api:
  dashboard: true
  insecure: false
  debug: false
  http:
    middlewares:
      - auth
      - ratelimit

ping: true

log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_network
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

http:
  middlewares:
    ratelimit:
      rateLimit:
        average: 100
        burst: 50
    auth:
      basicAuth:
        usersFile: "/etc/traefik/.htpasswd"

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: sloane@ec1c.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
