tunnel: your-tunnel-id
credentials-file: /etc/cloudflared/your-tunnel-id.json

ingress:
  - hostname: "*.ec1c.com"
    service: http://traefik:80
  - hostname: ec1c.com
    service: http://traefik:80
  - hostname: www.ec1c.com
    service: http://traefik:80
  - service: http_status:404
