tunnel: your-tunnel-id
credentials-file: /etc/cloudflared/your-tunnel-id.json

ingress:
  - hostname: jupyter.yourdomain.com
    service: http://jupyter:8888
  - hostname: dagster.yourdomain.com
    service: http://dagster:3000
  - hostname: searxng.yourdomain.com
    service: http://searxng:8889
  - service: http_status:404
