name: Infrastructure CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-configs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate Docker Compose files
      run: |
        docker-compose -f docker-compose.yml config
        docker-compose -f docker-compose.fail2ban.yml config
        
    - name: Validate Traefik config
      run: |
        docker run -v ${{ github.workspace }}/traefik:/etc/traefik:ro traefik:v2.10 traefik validate --check

  test-containers:
    runs-on: ubuntu-latest
    needs: validate-configs
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Create test environment
      run: |
        mkdir -p nginx/certs cloudflared
        touch .env
        echo "JUPYTER_TOKEN=test-token" >> .env
        echo "TUNNEL_TOKEN=${{ secrets.CF_TUNNEL_TOKEN }}" >> .env
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
        echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> .env
        
    - name: Build and test containers
      run: |
        docker-compose -f docker-compose.yml up -d
        docker-compose ps
        sleep 30 # Wait for services to initialize
        
    - name: Test service health
      run: |
        curl -f http://localhost:8888/api/status || exit 1
        curl -f http://localhost:3000/health || exit 1
        curl -f http://localhost:8889/status || exit 1
        
    - name: Run security scans
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        
    - name: Test fail2ban integration
      run: |
        docker-compose -f docker-compose.fail2ban.yml up -d
        sleep 10
        docker-compose exec -T fail2ban fail2ban-client status
        docker-compose logs fail2ban
        
    - name: Cleanup
      if: always()
      run: |
        docker-compose down -v
        docker system prune -f

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test-containers
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        if_key_exists: replace
        
    - name: Deploy to production
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        DEPLOY_PATH: /home/${{ secrets.SSH_USER }}/infrastructure
      run: |
        # Create deployment script
        echo "#!/bin/bash
        set -e
        cd \$DEPLOY_PATH

        # Ensure .env file exists and is not in git
        touch .env
        echo '.env' >> .gitignore

        # Pull latest code without overwriting .env
        git stash -u
        git pull origin main
        git stash pop || true

        # Update containers
        docker-compose pull
        docker-compose -f docker-compose.yml -f docker-compose.fail2ban.yml down
        docker-compose -f docker-compose.yml -f docker-compose.fail2ban.yml up -d

        # Cleanup
        docker system prune -f" > deploy.sh
        chmod +x deploy.sh
        
        # Copy deployment script and execute
        scp -o StrictHostKeyChecking=no deploy.sh $SSH_USER@$SSH_HOST:$DEPLOY_PATH/
        ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd $DEPLOY_PATH && ./deploy.sh"
        
    - name: Verify deployment
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        DEPLOY_PATH: /home/${{ secrets.SSH_USER }}/infrastructure
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd $DEPLOY_PATH && \
          docker-compose ps && \
          docker-compose logs --tail=50 && \
          echo 'Checking service health...' && \
          for service in \$(docker-compose ps --services); do
            echo \"Checking \$service...\"
            docker-compose ps \$service | grep -q \"healthy\" || exit 1
          done"

    - name: Notify on failure
      if: failure()
      run: |
        echo "Deployment failed! Check the logs for details."
        exit 1
