name: Container CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-configs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate Docker Compose files
      run: |
        docker-compose -f docker-compose.yml config
        docker-compose -f docker-compose.fail2ban.yml config
        
    - name: Validate Nginx config
      uses: jbergknoff/docker-nginx-validator@v1
      with:
        config-file: nginx/conf.d/reverse-proxy.conf

  test-containers:
    runs-on: ubuntu-latest
    needs: validate-configs
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and test containers
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.fail2ban.yml up -d
        docker-compose ps
        docker-compose exec reverse_proxy nginx -t
        docker-compose logs
        
    - name: Run security scans
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker-compose.yml'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        
    - name: Test fail2ban integration
      run: |
        # Simulate failed SSH attempts
        for i in {1..5}; do
          sshpass -p 'wrongpassword' ssh -o StrictHostKeyChecking=no user@localhost || true
        done
        
        # Verify IP is banned
        docker-compose exec fail2ban fail2ban-client status sshd
        docker-compose logs fail2ban

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test-containers
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push containers
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.fail2ban.yml build
        docker-compose -f docker-compose.yml -f docker-compose.fail2ban.yml push
